pipeline {
    agent {
        docker { 
            image 'ax3lrod/taskflow-ci:latest'
            args '-u root -v /var/run/docker.sock:/var/run/docker.sock --network host'
        }
    }
    
    environment {
        PROJECT_DIR = 'pertemuan-09-cicd/pbl-taskflow-go'
        GOCACHE = "${WORKSPACE}/.cache"
        DATABASE_URL = "postgres://taskflow:taskflow_secret@localhost:5432/taskflow?sslmode=disable"
        DOCKER_IMAGE = "fikriau/taskflow-api"
    }

    stages {
        stage('1. Preparation') {
            steps {
                checkout scm
                sh 'git config --global --add safe.directory "*"'
                dir("${env.PROJECT_DIR}") {
                    echo '📦 Downloading Dependencies...'
                    sh 'go mod download'
                }
            }
        }

        stage('2. Static Analysis') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo '🔍 Running go vet...'
                    sh 'go vet ./...'
                }
            }
        }

        stage('2.1 Security Audit: SAST') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo '🛡️ Running Gosec (Static Application Security Testing)...'
                    script {
                        sh 'go install github.com/securego/gosec/v2/cmd/gosec@v2.20.0'
                        // File ini dibuat di dalam folder PROJECT_DIR
                        sh '/go/bin/gosec -fmt json -out gosec-report.json ./...'
                    }
                }
            }
        }

        stage('3. Database Startup') {
            steps {
                script {
                    def dbContainerName = "db-container-${env.BUILD_ID}"
                    echo "🚀 Starting PostgreSQL Sidecar: ${dbContainerName}"
                    sh "docker run -d --name ${dbContainerName} -p 5432:5432 -e POSTGRES_DB=taskflow -e POSTGRES_USER=taskflow -e POSTGRES_PASSWORD=taskflow_secret postgres:16"
                    sh 'sleep 15'
                }
            }
        }

        stage('4. Unit Testing') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo '🧪 Running Unit Tests...'
                    sh "CGO_ENABLED=1 go test -v -race -buildvcs=false ./internal/service/... ./internal/validator/... ./internal/handler/..."
                }
            }
        }

        stage('5. Integration Testing') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo '🔗 Running Integration Tests...'
                    sh "CGO_ENABLED=1 DATABASE_URL='${env.DATABASE_URL}' go test -v -race -tags=integration -buildvcs=false ./internal/repository/..."
                }
            }
        }

        stage('6. Coverage Gate') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    script {
                        echo '📊 Checking Coverage (Minimum 75%)...'
                        sh "DATABASE_URL='${env.DATABASE_URL}' go test ./... -tags=integration -coverprofile=cov.out -buildvcs=false"
                        def coverage = sh(script: "go tool cover -func=cov.out | grep total | awk '{print \$3}' | sed 's/%//'", returnStdout: true).trim()
                        echo "Total Project Coverage: ${coverage}%"
                        
                        if (coverage.toFloat() < 75.0) {
                            error "❌ FAILED: Coverage (${coverage}%) di bawah batas minimal 75%!"
                        }
                    }
                }
            }
        }

        stage('7. Build Binary') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo '🏗️ Compiling Application...'
                    sh 'go build -buildvcs=false -o bin/taskflow-api ./cmd/server'
                }
            }
        }

        stage('8. CD - Build & Push Docker Hub') {
            when { branch 'main' }
            steps {
                script {
                    def commitSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def fullTag = "${env.DOCKER_IMAGE}:sha-${commitSha}"

                    echo "🚀 Memulai proses Build & Push untuk image: ${fullTag}"

                    withCredentials([usernamePassword(credentialsId: 'dockerhub-fikri', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
                        
                        dir("${env.PROJECT_DIR}") {
                            sh "docker build -t ${fullTag} ."
                            sh "docker push ${fullTag}"
                            
                            sh "docker tag ${fullTag} ${env.DOCKER_IMAGE}:latest"
                            sh "docker push ${env.DOCKER_IMAGE}:latest"
                        }
                        sh "docker logout"
                    }
                }
            }
        }

        stage('8.1 Security Audit: Container Scan') {
            steps {
                script {
                    def commitSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def fullTag = "${env.DOCKER_IMAGE}:sha-${commitSha}"
                    
                    echo "🛡️ Scanning Docker Image: ${fullTag}"
                    sh 'curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin'
                    // File ini dibuat di root WORKSPACE
                    sh "trivy image --severity HIGH,CRITICAL --exit-code 0 --format json --output trivy-report.json ${fullTag}"
                }
            }
        }
        
        stage('9. Deploy to VPS') {
            when { branch 'main' }
            steps {
                script {
                    echo "🚀 Deploying SHA image to VPS..."

                    def commitSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def IMAGE_TAG = "${env.DOCKER_IMAGE}:sha-${commitSha}" 

                    sshagent(credentials: ['vps-ssh']) {
                        sh """
                            ssh -o StrictHostKeyChecking=no kelompok6@10.4.89.175 '
                                set -e
                                cd /home/kelompok6/Devops-CI-CD-Kel-6-Jenkins/pertemuan-09-cicd/pbl-taskflow-go
                                git pull origin main
                                docker compose pull
                                docker compose down
                                export IMAGE_TAG=${IMAGE_TAG}
                                docker compose up -d --force-recreate
                            '
                        """
                    }

                    echo "✅ Deployment selesai."
                }
            }
        }

        stage('10. Smoke Test') {
            when { branch 'main' }
            steps {
                script {
                    echo "🔍 Memulai Smoke Test otomatis..."
                    def MAPPED_PORT = "8080"
                    sh """
                        RETRIES=10
                        COUNT=0
                        until curl -sf http://localhost:${MAPPED_PORT}/healt; do
                            COUNT=\$((COUNT+1))
                            if [ \$COUNT -ge \$RETRIES ]; then
                                echo "❌ FATAL: Health check gagal!"
                                exit 1
                            fi
                            sleep 2
                        done
                        curl -sf http://localhost:${MAPPED_PORT}/api/v1/stats || exit 1
                    """
                }
            }
        }

        stage('11. Promote to Stable') {
            when { branch 'main' }
            steps {
                script {
                   def commitSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                   def fullTag = "${env.DOCKER_IMAGE}:sha-${commitSha}"

                     withCredentials([usernamePassword(credentialsId: 'dockerhub-fikri', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                            sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
                            sh """
                                docker pull ${env.DOCKER_IMAGE}:stable || true
                                docker tag ${env.DOCKER_IMAGE}:stable ${env.DOCKER_IMAGE}:stable-prev || true
                                docker push ${env.DOCKER_IMAGE}:stable-prev || true
                                docker tag ${fullTag} ${env.DOCKER_IMAGE}:stable
                                docker push ${env.DOCKER_IMAGE}:stable
                            """
                            sh "docker logout"
                     }
                }
            }
        }
    }

    post {
        success {
            script {
                withCredentials([string(credentialsId: 'telegram-bot-token', variable: 'BOT_TOKEN'), string(credentialsId: 'telegram-chat-id', variable: 'CHAT_ID')]) {
                    def commitSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def message = "✅ *Pipeline Sukses*\n\n• *Commit*: ${commitSha}\n• *Laporan Security*: Tersedia di Artifacts"
                    sh "curl -s -X POST 'https://api.telegram.org/bot${BOT_TOKEN}/sendMessage' --data-urlencode 'chat_id=${CHAT_ID}' --data-urlencode 'parse_mode=Markdown' --data-urlencode 'text=${message}'"
                }
            }
        }

        failure {
            script {
                withCredentials([string(credentialsId: 'telegram-bot-token', variable: 'BOT_TOKEN'), string(credentialsId: 'telegram-chat-id', variable: 'CHAT_ID')]) {
                    def message = "❌ *Pipeline Gagal*\n\nPeriksa log untuk detail kegagalan."
                    sh "curl -s -X POST 'https://api.telegram.org/bot${BOT_TOKEN}/sendMessage' --data-urlencode 'chat_id=${CHAT_ID}' --data-urlencode 'parse_mode=Markdown' --data-urlencode 'text=${message}'"
                }
            }
        }

        always {
            echo '🧹 Membersihkan container...'
            script {
                def dbContainerName = "db-container-${env.BUILD_ID}"
                sh "docker rm -f ${dbContainerName} || true"
            }
            
            // BAGIAN PENTING: Mengumpulkan semua laporan ke dashboard utama
            echo '📦 Mengarsipkan semua laporan (SAST, Container Scan, Coverage)...'
            archiveArtifacts artifacts: '**/gosec-report.json, trivy-report.json, **/cov.out', allowEmptyArchive: true
        }
    }
}
